import type { NextRequest } from "next/server";
import { connectDB } from "@/lib/db/mongoose";
import { Complaint, SystemLog, User } from "@/models";
import { env } from "@/lib/config/env";
import { ok, fail, handleRoute } from "@/lib/api/response";
import { getSettings } from "@/lib/services/settings";
import { escalateComplaint, refreshDerived } from "@/lib/services/complaints";
import { logEvent, SYSTEM_ACTOR } from "@/lib/services/events";
import { drainMailQueue, notifyInApp, queueMail } from "@/lib/services/notify";
import { autoClosedForStudent, slaDigestForStaff } from "@/lib/mail/templates";
import { OPEN_STATUSES } from "@/lib/domain/constants";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const maxDuration = 60;

const HOUR = 3_600_000;
const DIGEST_SOURCE = "sla-digest";

/**
 * The scheduled sweep. Idempotent, safe to run every 15 minutes.
 *
 * Vercel Hobby cron only fires once per day, which cannot drive a 24-hour
 * escalation clock — so this endpoint is called by a free GitHub Actions
 * workflow (.github/workflows/cron.yml) and guarded by CRON_SECRET.
 *
 * Order matters: recompute -> escalate -> auto-close -> send mail, so that any
 * mail generated by this run is delivered in the same pass.
 */
async function runSweep() {
  await connectDB();
  const settings = await getSettings();
  const now = new Date();
  const cfg = settings.escalation;

  const report = {
    scanned: 0,
    priorityUpdated: 0,
    slaBreached: 0,
    autoEscalated: 0,
    level2Escalated: 0,
    autoClosed: 0,
    digestRecipients: 0,
    mailSent: 0,
    mailFailed: 0,
    errors: [] as string[],
  };

  /* --- 1 + 2: recompute priority and SLA breach flags on open complaints --- */
  const openComplaints = await Complaint.find({
    status: { $in: [...OPEN_STATUSES] },
    deletedAt: null,
  }).limit(1000);

  report.scanned = openComplaints.length;

  for (const complaint of openComplaints) {
    try {
      const wasBreached = complaint.sla.resolveBreached;
      const previousScore = complaint.priorityScore;

      await refreshDerived(complaint, now);

      if (!wasBreached && complaint.sla.resolveBreached) {
        report.slaBreached++;
        await logEvent({
          complaintId: complaint._id,
          complaintCode: complaint.code,
          actor: SYSTEM_ACTOR,
          action: "SLA_BREACHED",
          message: "The resolution deadline passed without the complaint being resolved.",
          meta: { dueAt: complaint.sla.resolveDueAt },
        });
      }

      if (Math.abs(previousScore - complaint.priorityScore) > 0.01) report.priorityUpdated++;
      await complaint.save();
    } catch (error) {
      report.errors.push(`priority:${complaint.code}:${(error as Error).message}`);
    }
  }

  /* --- 3: E2 — auto-escalate complaints nobody has touched for 24 h -------- */
  const staleCutoff = new Date(now.getTime() - cfg.autoEscalateStaleAfterHours * HOUR);
  const stale = await Complaint.find({
    status: { $in: ["SUBMITTED", "ACKNOWLEDGED", "REOPENED"] },
    escalationLevel: 0,
    lastActivityAt: { $lte: staleCutoff },
    deletedAt: null,
  }).limit(100);

  for (const complaint of stale) {
    try {
      const hours = Math.round((now.getTime() - complaint.lastActivityAt.getTime()) / HOUR);
      await escalateComplaint(
        complaint,
        `No action has been recorded on this complaint for ${hours} hours. It was escalated automatically.`,
        { id: null, name: "System", role: "SYSTEM" },
      );
      report.autoEscalated++;
    } catch (error) {
      report.errors.push(`escalate:${complaint.code}:${(error as Error).message}`);
    }
  }

  /* --- 4: E5 — level 1 -> level 2 after a further 48 h -------------------- */
  const level2Cutoff = new Date(now.getTime() - cfg.level2AfterHours * HOUR);
  const stillStuck = await Complaint.find({
    status: { $in: [...OPEN_STATUSES] },
    escalationLevel: 1,
    lastEscalatedAt: { $lte: level2Cutoff },
    deletedAt: null,
  }).limit(50);

  for (const complaint of stillStuck) {
    try {
      await escalateComplaint(
        complaint,
        `Still unresolved ${cfg.level2AfterHours} hours after being escalated to the Hostel Warden.`,
        { id: null, name: "System", role: "SYSTEM" },
      );
      report.level2Escalated++;
    } catch (error) {
      report.errors.push(`level2:${complaint.code}:${(error as Error).message}`);
    }
  }

  /* --- 5: E7 — auto-close resolved complaints after 72 h of silence ------- */
  const closeCutoff = new Date(now.getTime() - cfg.autoCloseResolvedAfterHours * HOUR);
  const toClose = await Complaint.find({
    status: "RESOLVED",
    "resolution.resolvedAt": { $lte: closeCutoff },
    deletedAt: null,
  }).limit(200);

  for (const complaint of toClose) {
    try {
      complaint.status = "VERIFIED_CLOSED";
      complaint.verification = {
        verifiedBy: null,
        verifiedAt: now,
        method: "AUTO",
      };
      complaint.lastActivityAt = now;
      await refreshDerived(complaint, now);
      await complaint.save();

      await logEvent({
        complaintId: complaint._id,
        complaintCode: complaint.code,
        actor: SYSTEM_ACTOR,
        action: "AUTO_CLOSED",
        fromStatus: "RESOLVED",
        toStatus: "VERIFIED_CLOSED",
        message: `Closed automatically — no response from the student for ${cfg.autoCloseResolvedAfterHours} hours.`,
      });

      await queueMail(
        [complaint.student.email],
        autoClosedForStudent(
          {
            code: complaint.code,
            title: complaint.title,
            description: complaint.description,
            hostel: complaint.hostel,
            category: complaint.category,
            severity: complaint.severity,
            status: "VERIFIED_CLOSED",
            studentName: complaint.student.name,
            regNo: complaint.student.regNo,
            createdAt: complaint.createdAt,
          },
          String(complaint._id),
        ),
        { relatedComplaint: complaint._id },
      );

      await notifyInApp(complaint.student.userId, {
        type: "AUTO_CLOSED",
        title: `${complaint.code} closed automatically`,
        body: "No response was received after the work was marked resolved.",
        link: `/student/complaints/${complaint._id}`,
        tone: "info",
      });

      report.autoClosed++;
    } catch (error) {
      report.errors.push(`autoclose:${complaint.code}:${(error as Error).message}`);
    }
  }

  /* --- 6: once a day, e-mail staff a digest of everything still overdue --- */
  try {
    report.digestRecipients = await sendSlaDigest(now);
  } catch (error) {
    report.errors.push(`digest:${(error as Error).message}`);
  }

  /* --- 7: deliver everything queued (including mail generated above) ------ */
  const mail = await drainMailQueue(40);
  report.mailSent = mail.sent;
  report.mailFailed = mail.failed;

  await SystemLog.create({
    level: report.errors.length ? "WARN" : "INFO",
    source: "cron-sweep",
    message: `Sweep complete: ${report.autoEscalated} escalated, ${report.autoClosed} auto-closed, ${report.slaBreached} newly breached.`,
    meta: report,
  });

  return report;
}

/**
 * The sweep runs every 15 minutes, but this digest must not. It sends only when
 * the last one was more than DIGEST_INTERVAL_HOURS ago, which the SystemLog
 * entry written at the end records — no extra collection, and it survives
 * redeploys because the state lives in the database rather than in memory.
 *
 * An RT is sent only their own hostel's overdue complaints; the Warden and the
 * Coordinator get all three hostels. Nobody is e-mailed when nothing is overdue.
 */
const DIGEST_INTERVAL_HOURS = 20;

async function sendSlaDigest(now: Date): Promise<number> {
  const lastRun = await SystemLog.findOne({ source: DIGEST_SOURCE })
    .sort({ createdAt: -1 })
    .select("createdAt")
    .lean();

  if (lastRun && now.getTime() - new Date(lastRun.createdAt).getTime() < DIGEST_INTERVAL_HOURS * HOUR) {
    return 0;
  }

  const overdue = await Complaint.find({
    status: { $in: [...OPEN_STATUSES] },
    "sla.resolveBreached": true,
    deletedAt: null,
  })
    .sort({ priorityScore: -1 })
    .limit(200)
    .select("code title hostel sla.resolveDueAt")
    .lean();

  // Still log the run, so an empty day does not make tomorrow send twice.
  if (overdue.length === 0) {
    await SystemLog.create({
      level: "INFO",
      source: DIGEST_SOURCE,
      message: "Daily SLA digest skipped — nothing is overdue.",
      meta: { overdue: 0, recipients: 0 },
    });
    return 0;
  }

  const rows = overdue.map((c) => ({
    id: String(c._id),
    code: c.code,
    title: c.title,
    hostel: c.hostel,
    overdueHours: Math.max(0, (now.getTime() - new Date(c.sla.resolveDueAt).getTime()) / HOUR),
  }));

  const staff = await User.find({
    isActive: true,
    role: { $in: ["RT", "WARDEN", "COORDINATOR"] },
  })
    .select("name email role hostel notificationPrefs")
    .lean();

  let recipients = 0;

  for (const member of staff) {
    if (member.notificationPrefs?.email === false) continue;

    const theirs = member.role === "RT" ? rows.filter((r) => r.hostel === member.hostel) : rows;
    if (theirs.length === 0) continue;

    await queueMail([member.email], slaDigestForStaff(member.name, theirs));
    recipients++;
  }

  await SystemLog.create({
    level: "WARN",
    source: DIGEST_SOURCE,
    message: `Daily SLA digest sent to ${recipients} staff member(s) covering ${rows.length} overdue complaint(s).`,
    meta: { overdue: rows.length, recipients },
  });

  return recipients;
}

function authorised(request: NextRequest): boolean {
  const secret = env.cronSecret;
  if (!secret) return env.isDev; // no secret configured: allow only in development
  const header = request.headers.get("x-cron-secret");
  const bearer = request.headers.get("authorization")?.replace(/^Bearer\s+/i, "");
  return header === secret || bearer === secret;
}

export async function POST(request: NextRequest) {
  return handleRoute(async () => {
    if (!authorised(request)) {
      return fail("FORBIDDEN", "Invalid or missing cron secret.");
    }
    const report = await runSweep();
    return ok(report);
  });
}

// Vercel Cron issues a GET; the same guard applies.
export async function GET(request: NextRequest) {
  return POST(request);
}
